package com.trading.algo.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * One row per trade signal generated by the Opening Candle Strategy backtest.
 *
 * Strategy rules:
 *  C1 = 9:15–9:30 candle  → strong bullish/bearish, wick ratio >= threshold
 *  C2 = 9:30–9:45 candle  → confirms by trading past 50% of C1 but not beyond C1 high/low
 *  Entry at close of C2, SL = C1 high/low ± 0.015%, Target = 2.5× risk
 */
@Entity
@Table(name = "backtest_trade")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class BacktestTrade {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String    symbol;
    private LocalDate tradeDate;

    @Enumerated(EnumType.STRING)
    private Direction direction;   // BUY or SELL

    // ── Candle 1 (9:15–9:30) ──────────────────────────────────────────────
    private double c1Open;
    private double c1High;
    private double c1Low;
    private double c1Close;
    private double c1WickRatio;    // body/range — must be >= minWickRatio

    // ── Candle 2 (9:30–9:45) ──────────────────────────────────────────────
    private double c2Open;
    private double c2High;
    private double c2Low;
    private double c2Close;

    // ── Trade levels ──────────────────────────────────────────────────────
    private double entryPrice;
    private double stopLoss;
    private double target;
    private double riskPoints;     // entry - SL (absolute)
    private double rewardPoints;   // target - entry (absolute)

    // ── Outcome ───────────────────────────────────────────────────────────
    @Enumerated(EnumType.STRING)
    private Outcome outcome;       // TARGET_HIT / SL_HIT / EOD_EXIT / OPEN

    private double exitPrice;
    private double pnlPoints;      // exitPrice - entryPrice (negative for loss)
    private double pnlPercent;     // pnlPoints / entryPrice * 100
    private double actualRR;       // pnlPoints / riskPoints

    /** Latest intraday price change from the 9:15 opening price; used only to rank live scan alerts. */
    @Transient
    private double signalPriceChangePercent;

    /**
     * Quantity calculated from fixed risk:
     *   quantity = floor(fixedRiskRupees / riskPoints)
     *   e.g. risk=10pts, fixedRisk=₹10000 → qty=1000 shares
     */
    @Column(name = "quantity", columnDefinition = "INT DEFAULT 0")
    @Builder.Default
    private Integer quantity = 0;

    /** Actual risk in rupees = quantity × riskPoints (≈ fixedRiskRupees, may vary due to floor) */
    @Column(name = "risk_rupees", columnDefinition = "DECIMAL(10,2) DEFAULT 0")
    @Builder.Default
    private Double riskRupees = 0.0;

    /** Actual P&L in rupees = pnlPoints × quantity */
    @Column(name = "pnl_rupees", columnDefinition = "DECIMAL(10,2) DEFAULT 0")
    @Builder.Default
    private Double pnlRupees = 0.0;

    /**
     * POINT 2 — Volume flag.
     * True if C1 volume >= 1.5× C2 volume (proxy for strong opening volume).
     * Full 5-day avg volume check not possible in backtest without extra API calls.
     * Instead: C1 volume vs C2 volume ratio is a good intraday proxy.
     * Flagged in Telegram alert with 🔥 if true.
     */
    /**
     * True if C1 volume >= 1.5× C2 volume — strong opening participation.
     * Used as an informational flag in Telegram (🔥), NOT a trade filter.
     * All setups are valid regardless; this just highlights high-volume ones.
     */
    @Column(name = "volume_flag")
    @Builder.Default
    private Boolean volumeFlag = false;

    /** C1 candle volume — used to compute volumeFlag */
    @Column(name = "c1_volume")
    private Long c1Volume;

    @Column(name = "exit_candle_time")
    private LocalDateTime exitCandleTime;

    // ── Previous day OHLC ───────────────────────────────────────────────────
    @Column(name = "prev_day_open", columnDefinition = "DECIMAL(10,2)")
    private Double prevDayOpen;

    @Column(name = "prev_day_high", columnDefinition = "DECIMAL(10,2)")
    private Double prevDayHigh;

    @Column(name = "prev_day_low", columnDefinition = "DECIMAL(10,2)")
    private Double prevDayLow;

    @Column(name = "prev_day_close", columnDefinition = "DECIMAL(10,2)")
    private Double prevDayClose;

    // ── C3 candle (first candle closing above C2 high on BUY / below C2 low on SELL) ──
    @Column(name = "c3_open", columnDefinition = "DECIMAL(10,2)")
    private Double c3Open;

    @Column(name = "c3_high", columnDefinition = "DECIMAL(10,2)")
    private Double c3High;

    @Column(name = "c3_low", columnDefinition = "DECIMAL(10,2)")
    private Double c3Low;

    @Column(name = "c3_close", columnDefinition = "DECIMAL(10,2)")
    private Double c3Close;

    // ── Gap flags (replaced by prev-day level categories) ───────────────────────
    // gapUp and gapDown removed — replaced by c1AbovePrevHigh / c1AbovePrevLow

    /** BUY: true if C1 open > previous day high. SELL: not used. */
    @Column(name = "c1_above_prev_high")
    @Builder.Default
    private Boolean c1AbovePrevHigh = false;

    /** SELL: true if C1 open > previous day low. BUY: not used. */
    @Column(name = "c1_above_prev_low")
    @Builder.Default
    private Boolean c1AbovePrevLow = false;

    @Column(name = "created_at")
    private LocalDateTime createdAt;

    // ── Enums ─────────────────────────────────────────────────────────────

    public enum Direction { BUY, SELL }

    public enum Outcome {
        TARGET_HIT,     // price reached 2.5R target
        SL_HIT,         // price hit original SL (before 1.5R)
        BREAKEVEN_EXIT, // 1.5R hit → SL moved to breakeven → stopped out at entry (zero loss)
        EOD_EXIT,       // neither hit by 3:15 PM — exit at market
        OPEN            // backtest not yet resolved (shouldn't persist)
    }
}
