package com.trading.algo.entity;

import java.time.LocalDate;
import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * One row per trade signal generated by the Opening Candle Strategy backtest.
 *
 * Strategy rules:
 *  C1 = 9:15–9:30 candle  → strong bullish/bearish, wick ratio >= threshold
 *  C2 = 9:30–9:45 candle  → confirms by trading past 50% of C1 but not beyond C1 high/low
 *  Entry at close of C2, SL = C1 high/low ± 0.015%, Target = 2.5× risk
 */
@Entity
@Table(name = "backtest_trade")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class BacktestTrade {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String    symbol;
    private LocalDate tradeDate;

    @Enumerated(EnumType.STRING)
    private Direction direction;   // BUY or SELL

    // ── Candle 1 (9:15–9:30) ──────────────────────────────────────────────
    private double c1Open;
    private double c1High;
    private double c1Low;
    private double c1Close;
    private double c1WickRatio;    // body/range — must be >= minWickRatio

    // ── Candle 2 (9:30–9:45) ──────────────────────────────────────────────
    private double c2Open;
    private double c2High;
    private double c2Low;
    private double c2Close;

    // ── Trade levels ──────────────────────────────────────────────────────
    private double entryPrice;
    private double stopLoss;
    private double target;
    private double riskPoints;     // entry - SL (absolute)
    private double rewardPoints;   // target - entry (absolute)

    // ── Outcome ───────────────────────────────────────────────────────────
    @Enumerated(EnumType.STRING)
    private Outcome outcome;       // TARGET_HIT / SL_HIT / EOD_EXIT / OPEN

    private double exitPrice;
    private double pnlPoints;      // exitPrice - entryPrice (negative for loss)
    private double pnlPercent;     // pnlPoints / entryPrice * 100
    private double actualRR;       // pnlPoints / riskPoints

    /**
     * Quantity calculated from fixed risk:
     *   quantity = floor(fixedRiskRupees / riskPoints)
     *   e.g. risk=10pts, fixedRisk=₹10000 → qty=1000 shares
     */
    private int    quantity;

    /** Actual risk in rupees = quantity × riskPoints (≈ fixedRiskRupees, may vary due to floor) */
    @Column(name = "risk_rupees")
    private double riskRupees;

    /** Actual P&L in rupees = pnlPoints × quantity */
    @Column(name = "pnl_rupees")
    private double pnlRupees;

    @Column(name = "exit_candle_time")
    private LocalDateTime exitCandleTime;

    @Column(name = "created_at")
    private LocalDateTime createdAt;

    // ── Enums ─────────────────────────────────────────────────────────────

    public enum Direction { BUY, SELL }

    public enum Outcome {
        TARGET_HIT,   // price reached 2.5× target
        SL_HIT,       // price hit stop loss
        EOD_EXIT,     // neither hit by 3:20 PM — exit at market
        OPEN          // backtest not yet resolved (shouldn't persist)
    }
}