package com.trading.algo.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * One row per trade signal generated by the IPO Breakout Strategy backtest.
 *
 * Strategy rules:
 *  - First candle = listing day or first available candle after listing date
 *  - Entry when any subsequent candle closes above first candle high
 *  - Stop loss = low of breakout candle
 *  - Risk-reward = 1:3
 *  - Trail SL to entry price at 1:3 (book 50% quantity)
 *  - Exit remaining 50% at 1:6
 */
@Entity
@Table(name = "ipo_backtest_trade")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class IpoBacktestTrade {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String symbol;
    private String companyName;
    private LocalDate listingDate;
    private LocalDate tradeDate;

    // ── First candle (reference candle) ────────────────────────────────────
    private LocalDate firstCandleDate;
    private double firstCandleOpen;
    private double firstCandleHigh;
    private double firstCandleLow;
    private double firstCandleClose;

    // ── Breakout candle (daily) ────────────────────────────────────────────
    private LocalDate breakoutDate;
    private double breakoutOpen;
    private double breakoutHigh;
    private double breakoutLow;
    private double breakoutClose;

    // ── Weekly breakout candle ────────────────────────────────────────────
    private LocalDate weeklyBreakoutDate;
    private double weeklyBreakoutOpen;
    private double weeklyBreakoutHigh;
    private double weeklyBreakoutLow;
    private double weeklyBreakoutClose;

    // ── Weekly trade levels ───────────────────────────────────────────────
    private double weeklyEntryPrice;
    private double weeklyStopLoss;
    private double weeklyTarget1;
    private double weeklyTarget2;
    private double weeklyRiskPoints;
    private double weeklyReward1Points;
    private double weeklyReward2Points;

    // ── Weekly outcome ────────────────────────────────────────────────────
    @Enumerated(EnumType.STRING)
    private Outcome weeklyOutcome;

    private double weeklyExitPrice;
    private double weeklyPnlPoints;
    private double weeklyPnlPercent;
    private double weeklyActualRR;

    // ── Weekly exit details ────────────────────────────────────────────────
    private LocalDateTime weeklyExitTime;
    private String weeklyExitReason;

    // ── Weekly trailing SL status ─────────────────────────────────────────
    private boolean weeklySlTrailedToBreakeven;
    private LocalDateTime weeklyTrailTime;

    // ── Trade levels ─────────────────────────────────────────────────────
    private double entryPrice;        // breakout close
    private double stopLoss;          // breakout low
    private double target1;           // 1:3 target (entry + 3 * risk)
    private double target2;           // 1:6 target (entry + 6 * risk)
    private double riskPoints;        // entry - SL
    private double reward1Points;     // target1 - entry
    private double reward2Points;     // target2 - entry

    // ── Quantity management ───────────────────────────────────────────────
    private int totalQuantity;        // full position size
    private int bookedQuantity;       // quantity booked at 1:3 (50%)
    private int remainingQuantity;    // quantity held for 1:6 target

    // ── Outcome ───────────────────────────────────────────────────────────
    @Enumerated(EnumType.STRING)
    private Outcome outcome;

    private double exitPrice;
    private double pnlPoints;
    private double pnlPercent;
    private double actualRR;

    // ── Exit details ──────────────────────────────────────────────────────
    private LocalDateTime exitTime;
    private String exitReason;

    // ── Trailing SL status ─────────────────────────────────────────────────
    private boolean slTrailedToBreakeven;
    private LocalDateTime trailTime;

    @Column(name = "created_at")
    private LocalDateTime createdAt;

    // ── Enums ─────────────────────────────────────────────────────────────

    public enum Outcome {
        TARGET1_HIT,      // 1:3 target hit - 50% booked, SL trailed to entry
        TARGET2_HIT,      // 1:6 target hit - remaining 50% booked
        SL_HIT,           // Stop loss hit (before any target)
        SL_HIT_TRAILED,   // Stop loss hit after trailing to breakeven
        EOD_EXIT,         // Neither hit by market close
        NO_BREAKOUT       // No breakout occurred during backtest period
    }
}
