spring.application.name=AlgoTrading

# ===============================
# MYSQL CONFIG
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/algotrading
spring.datasource.username=root
spring.datasource.password=root

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# CONNECTION POOL (OPTIONAL)
# ===============================
spring.datasource.hikari.maximum-pool-size=10

# ===============================
# SERVER CONFIG
# ===============================
server.port=8080

telegram.bot.token=8271537265:AAGyYMTjdOELAcs2Iq4EvaT60f8-QvHH5v0
telegram.chat.id=780646088

upstox.access.token=eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDQ4NzUiLCJqdGkiOiI2OWNjY2JhMjQxZWU5NzdmYjA2MmRhMTAiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaXNQbHVzUGxhbiI6ZmFsc2UsImlhdCI6MTc3NTAyOTE1NCwiaXNzIjoidWRhcGktZ2F0ZXdheS1zZXJ2aWNlIiwiZXhwIjoxNzc1MDgwODAwfQ.MPfAyFNOGVrf_SFSfbehiymF2ySvJu8GqD5Qt89dr6Y
upstox.api.key=de32ef46-2d03-428c-903c-a82ebb8a7fc4
upstox.api.secret=9eiwfmkz4e



